service: suspicious-serverless

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod

package:
  artifact: dst.zip

functions:
  api:
    handler: api.handler
    events:
      - http:
          path: /{proxy+}
          method: any
