service: suspicious-serverless

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  environment:
    DEBUG: "suspicious-serverless:*"
#    DEBUG: "suspicious-serverless:*,puppeteer:*"

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

functions:
  api:
    handler: api.handler
    timeout: 120
    events:
      - http:
          path: /{proxy+}
          method: any
