service: suspicious-serverless

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod

plugins:
  - serverless-webpack

functions:
  api:
    handler: api.handler
    timeout: 60
    events:
      - http:
          path: /{proxy+}
          method: any
