service: suspicious-serverless

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - "@vingle/serverless-tag-plugin"

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
    prune:
      automatic: true
      number: 5

functions:
  api:
    handler: api.handler
    timeout: 120
    events:
      - http:
          path: /{proxy+}
          method: any
