service: microservice-template

plugins:
  - sentry-serverless-plugin

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod

package:
  artifact: dst.zip

functions:
  hello:
    handler: handlers.hello
    events:
      - http:
          path: hello
          method: get
