service: suspicious-serverless

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  logRetentionInDays: 30

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - "@vingle/serverless-tag-plugin"

custom:
  webpack:
    includeModules:
      forceInclude:
        - "@serverless-chrome/lambda"
      forceExclude:
        - aws-sdk
  prune:
    automatic: true
    number: 5

functions:
  api:
    handler: src/api/index.handler
    timeout: 120
    memorySize: 1024
    events:
      - http:
          path: /{proxy+}
          method: any
