service: suspicious-serverless

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  api:
    handler: api.handler
    timeout: 120
    events:
      - http:
          path: /{proxy+}
          method: any
